version: "3.8"

services:
  app:
    build:
      context: . # Создаю образ из текущей директории
      dockerfile: Dockerfile
    container_name: my_app
    ports:
      - "8000:8000" # Пробрасываею порт приложения
    environment:
      NODE_ENV: production
      DATABASE_URL: ${DATABASE_URL} # Ссылка на базу данных
      MINIO_URL: http://minio:9000 # Внутренний URL MinIO
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
      MINIO_BUCKET_NAME: ${MINIO_BUCKET_NAME}
    depends_on:
      - minio # Сначала запускаю MinIO

  minio:
    container_name: minio_storage
    image: quay.io/minio/minio
    restart: always
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    ports:
      - "9000:9000" # S3 API
      - "9001:9001" # Консоль управления
    volumes:
      - ./minio-data:/data # Данные MinIO сохраняются в локальной директории
    command: server /data --console-address ":9001"
